name: CI Tests

on:
  push: [master]
  pull_request: [master]

jobs:
  ci_tests:
    name: Documentation build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up python ${{ matrix.python }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Build documentation
      run: |
        tox -e build_docs
